### ISSUE TITLE
UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by boomer30** [googlesamples/mediapipe#165] opened 2023-06-13 14:58 UTC
Getting the following error when I start the app

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.examples.poselandmarker, PID: 23887
    kotlin.UninitializedPropertyAccessException: lateinit property poseLandmarkerHelper has not been initialized
        at com.google.mediapipe.examples.poselandmarker.fragment.CameraFragment$initBottomSheetControls$8.onItemSelected(CameraFragment.kt:254)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7884)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by boomer30** [comment] 2023-06-13 18:51
I upgraded to Flamingo and upgraded Gradle to 8.0. I no longer get the error above, but the app is still shutting down immediately after opening.

**Comment by PaulTR** [comment] 2023-06-16 14:46
Is there an error for it after all of the updates and whatnot? I just tried it on a physical pixel 7 and cannot reproduce the problem. If it's a lateinit issue, we might just need to wrap the code with the helper with

if(this::poseLandmarkerHelper.isInitialized) {
}

**Comment by boomer30** [comment] 2023-06-19 13:51
It does not produce an error. It just shuts down immediately

**Comment by PaulTR** [comment] 2023-06-27 19:05
I'm going to try and wrap all the usages of poseLandmarkerHelper in the isInitialized flag check, so we'll see how that goes (I never was able to replicate the issue, unfortunately, but that's the joys of race conditions :)) Closing this out, but let me know if you still have issues after that fix. Thanks!

**Closed by PaulTR** 2023-06-27 19:05 UTC
